### ISSUE TITLE
BME280 Pin Connection

### ISSUE THREAD

**Issue by fabioetec** [VekotinVerstas/Digitalisaatiopurkki#1]
Hi,

Great work!!!
Which pins did you use to connect BME280 to TTGO?

Thank you!

**Comment by aapris** [comment]
Pins are mentioned here:
https://github.com/VekotinVerstas/Digitalisaatiopurkki/blob/19d2bebb7bd011442a4c064d5403b36c3b87d036/Digitalisaatiopurkki.ino#L103
